package home.logger.rest;

import home.common.data.LogOption;

public class LoggerTest {

	public static void main(String[] args) throws InterruptedException {
		RemoteLogImpl.setLogFileName("InitFileNae");
//		RemoteLogImpl.setLogLevel(RemoteLogLevel.ERROR);
		RemoteLogImpl.setLogOption(LogOption.FILE_FIXED_SIZE_NO_DATE);

		RemoteLogMaster log = RemoteLogImpl.getLogger(LoggerTest.class);
		
//		LogMaster log2 = LogImpl.getLogger(Connect.class);
		
		System.out.println("Log class name: " + log.getClassName() + " logger file name: " + log.getInitializedLogFileName());
		
//		System.out.println("Log2 class name: " + log2.getClassName());
//		int i = 0;
		for(int i = 0  ; i < 5 ; i ++) {
			System.out.println("I = " + i);
			log.debug("Big debug in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf" + i);
			log.debug("Big debug2 in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf Big debug2 in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf Big debug2 in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf Big debug2 in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf Big debug2 in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf Big debug2 in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\\\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf" + i);
			log.info("Big Info in loop: -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear 2a22ssafdfdffffffffffffffffffffffffffffffffsdfsdfsdfsdf sd fsdffffffffffffffffffffff sdf" + i);
			log.error("Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear " + i);
			log.error("Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear Error2 is generated -------a al lla a lll  nmot tttoooa a  new random generated string that can \\n take a long time ro run but this is a test so now i must bu very careful. but not as mucjk careful as the next rabbit ot come into that hoel.. that glory hole that is not to be touched and pocked butcaust it won't lone it .. repear " + i);
			Thread.sleep(500);
		}
		
		
	}

}
